/**:
  ros__parameters:
  # DBW joystick node
    ignore: false
    enable: true
    svel: 0.0
  # Shared with DBW CAN node
    max_steer_angle: 470.0
  # joy_linux node
    dev: "/dev/input/js0"
    deadzone: 0.5
    autorepeat_rate: 20.0
    coalesce_interval: 0.05
